# Generated by Django 5.2.7 on 2025-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_year',
            field=models.CharField(max_length=30),
        ),
    ]
