# Generated by Django 5.2.7 on 2025-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_education_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
